server:
  port: 8080
  tomcat:
    uri-encoding: UTF-8
spring:
  datasource:
    username: root
    password: 123456
    url: jdbc:mysql://localhost:3306/hisplat?useUnicode=true&characterEncoding=utf-8&useSSL=true&serverTimezone=Asia/Shanghai
    driver-class-name: com.mysql.cj.jdbc.Driver
  redis:
    host: localhost
    timeout: 2000s
    #shiro里的加密方式 和  加密次数，
    hashAlgorithmName: md5
    hashIterations: 2
    port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
mybatis:
  mapper-locations: classpath:mapping/*Mapper.xml
  type-aliases-package: com.mh.hisplat.bean
logging:
  level:
    com:
      mh:
        hisplat:
          dao: debug
# pagehelper
pagehelper:
  helperDialect: mysql
  reasonable: true
  supportMethodsArguments: true
  params: count=countSql